---
name: setup-python-tools-scripts
description: Setup 'python-tools-scripts'

inputs:
  cache-prefix:
    required: true
    type: string
    description: Seed used to invalidate caches
  cwd:
    type: string
    description: The directory the salt checkout is located in
    default: "."

outputs:
  version:
    value: ${{ steps.get-version.outputs.version }}
  cache-prefix:
    value: ${{ steps.cache-hash.outputs.cache-prefix }}


env:
  PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple


runs:
  using: composite

  steps:

    - name: Get Python Version
      id: get-python-version
      uses: ./.github/actions/get-python-version
      with:
        python-binary: python3

    - uses: ./.github/actions/setup-poetry
      id: setup-poetry
      with:
        cache-prefix: ${{ inputs.cache-prefix }}

    - name: Define Cache Hash
      id: cache-hash
      shell: bash
      run: |
        echo "TOOLS_VIRTUALENV_CACHE_SEED=${{ steps.setup-poetry.outputs.poetry-hash }}" | tee -a "${GITHUB_ENV}"
        echo "cache-prefix=${{ steps.setup-poetry.outputs.poetry-hash }}" | tee -a "${GITHUB_OUTPUT}"

    - name: Restore Python Tools Virtualenvs Cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cwd }}/.tools-venvs
        key: ${{ steps.setup-poetry.outputs.poetry-hash }}|tools-venvs

    - name: Install 'python-tools-scripts'
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: |
        poetry install --no-root --only=tools --sync

    - name: Get 'python-tools-scripts' Version
      id: get-version
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: |
        # The first time `tools` runs with newer virtual enviroments we need to disregard the output
        poetry run tools --debug --version
        VERSION=$(poetry run tools --version | tail -n 1)
        echo "version=$VERSION" >> "${GITHUB_OUTPUT}"
