---
default_language_version:
  python: python3

exclude: ^(doc/_static/.*|doc/_themes/.*)$
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args:
          - --markdown-linebreak-ext=md
        exclude: >
          (?x)^(
            pkg/macos/pkg-resources/.*\.rtf
          )$

      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args:
          - --fix=lf
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-ast             # Simply check whether files parse as valid python.
        exclude: >
          (?x)^(
            templates/.*
          )$
      - id: check-case-conflict   # Check for files with names that would conflict on a
                                  # case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-json            # Attempts to load all json files to verify syntax.
      - id: check-symlinks        # Checks for symlinks which do not point to anything.
      - id: debug-statements      # Check for debugger imports and py37+ breakpoint() calls in python source.
        exclude: >
          (?x)^(
            templates/.*
          )$
      - id: fix-byte-order-marker # removes UTF-8 byte order marker
      - id: forbid-submodules     # forbids any submodules in the repository.
      - id: fix-encoding-pragma   # Remove `# -*- coding: utf-8 -*-` from the top of python files.
        args:
          - --remove
        exclude: >
          (?x)^(
            salt/ext/.*
          )$

  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
      - id: poetry-lock
        args:
          - --no-update
      - id: poetry-check

  - repo: https://github.com/saltstack/python-tools-scripts
    rev: "0.20.5"
    hooks:
      - id: tools-poetry
        alias: check-changelog-entries
        name: Check Changelog Entries
        args:
          - pre-commit
          - changelog
          - pre-commit-checks

      - id: tools-poetry
        alias: generate-workflows
        name: Generate GitHub Workflow Templates
        files: ^(cicd/shared-gh-workflows-context\.yml|tools/precommit/workflows\.py|.github/workflows/templates/.*)$
        pass_filenames: false
        args:
          - pre-commit
          - workflows
          - generate-workflows

      - id: tools-poetry
        alias: actionlint
        name: Lint GitHub Actions Workflows
        files: "^.github/workflows/"
        types:
          - yaml
        args:
          - pre-commit
          - workflows
          - actionlint

      - id: tools-poetry
        alias: check-docs
        name: Check Docs
        files: ^(salt/.*\.py|doc/ref/.*\.rst)$
        args:
          - pre-commit
          - docs
          - check

      - id: tools-poetry
        alias: check-docstrings
        name: Check docstrings
        files: salt/.*\.py$
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
            )$
        args:
          - pre-commit
          - docstrings
          - check

      - id: tools-poetry
        alias: check-known-missing-docstrings
        name: Check Known Missing Docstrings
        stages: [manual]
        files: salt/.*\.py$
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
            )$
        args:
          - pre-commit
          - docstrings
          - check

      - id: tools-poetry
        alias: loader-check-virtual
        name: Check loader modules __virtual__
        files: salt/.*\.py$
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
            )$
        args:
          - pre-commit
          - salt-loaders
          - check-virtual

      - id: tools-poetry
        alias: check-filemap
        name: Check Filename Map Change Matching
        files: ^tests/(filename_map\.yml|.*\.py)$
        pass_filenames: false
        args:
          - pre-commit
          - filemap
          - check

      - id: tools-poetry
        alias: lint-salt
        name: Lint Salt
        files: ^((setup|noxfile)|(salt|tools)/.*)\.py$
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
            )$
        args:
          - lint
          - salt

      - id: tools-poetry
        alias: lint-tests
        name: Lint Tests
        files: ^tests/.*\.py$
        args:
          - lint
          - tests

  # ----- Code Formatting ------------------------------------------------------------------------------------------->
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        name: Upgrade code to Py3.7+
        args: [--py37-plus, --keep-mock]
        exclude: >
          (?x)^(
            salt/client/ssh/ssh_py_shim.py
            |
            salt/client/ssh/wrapper/pillar.py
            |
            salt/ext/.*\.py
          )$

  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 1.1.0
    hooks:
      - id: remove-import-headers

  - repo: https://github.com/saltstack/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 2.5.2
    hooks:
      - id: salt-rewrite
        alias: rewrite-docstrings
        name: Salt docstrings auto-fixes
        files: ^salt/.*\.py$
        args: [--silent, -F, fix_docstrings]
        exclude: >
            (?x)^(
                salt/ext/.*
            )$

      - id: salt-rewrite
        alias: rewrite-tests
        name: Rewrite Salt's Test Suite
        files: ^tests/.*\.py$
        args: [--silent, -E, fix_asserts, -E, fix_docstrings]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: ['toml']
        # This tells pre-commit not to pass files to isort.
        # This should be kept in sync with pyproject.toml
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
            )$

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        # This tells pre-commit not to pass files to black.
        # This should be kept in sync with pyproject.toml
        exclude: >
            (?x)^(
                salt/client/ssh/ssh_py_shim\.py|
                templates/.*|
                salt/ext/.*|
            )$

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^doc/.*\.rst
        additional_dependencies:
          - black==24.2.0

  # <---- Code Formatting --------------------------------------------------------------------------------------------

  # ----- Security -------------------------------------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.7"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against Salt
        args: [--silent, -lll, --skip, "B701,B324"]
        exclude: >
            (?x)^(
                templates/.*|
                salt/ext/.*|
                tests/.*
            )$
        additional_dependencies: ['importlib_metadata<5']
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.7"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, "B701,B324"]
        files: ^tests/.*
        exclude: ^tests/minionswarm\.py
        additional_dependencies: ['importlib_metadata<5']
  # <---- Security ---------------------------------------------------------------------------------------------------

  # ----- Pre-Commit ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        alias: mypy-tools
        name: Run mypy against tools
        files: ^tools/.*\.py$
        exclude: >
            (?x)^(
                templates/.*|
                salt/.*|
            )$
        additional_dependencies:
          - attrs
          - rich
          - types-attrs
          - types-pyyaml
          - types-requests
          - python-tools-scripts==0.20.5
  # <---- Pre-Commit -------------------------------------------------------------------------------------------------
