name: Build Linux Onedir x86_64

on: [push, pull_request]

jobs:
  build:
    name: Build Onedir

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build onedir
      run: CONTAINER_IMAGE=dwoz1/cicd:onedir-centos7-x86_64 ./pkg/onedir.sh

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Salt Onedir X86_64
        path: salt*.tar.xz

  dependencies:
    needs: build
    runs-on: macos-12
    name: Install Dependencies on VM

    steps:
    - uses: actions/checkout@v3

    - name: Fetch Artifact
      uses: actions/download-artifact@v3
      with:
        name: Salt Onedir X86_64

    - name: Install Requirements
      uses: leleliu008/github-actions-vagrant@v2
      with:
        mem: 4096
        box: salt-project-ci/debian-11
        run: |
          sudo env PATH=salt-artifacts/salt/bin:${PATH} nox --force-color --install-only -e 'pytest-zeromq-3(coverage=True)'

  test:
    needs: dependencies
    runs-on: macos-12
    name: Run Tests in VM
    strategy:
      fail-fast: false
      matrix:
        test-paths:
          - tests/unit tests/pytests/unit
          - tests/pytests/functional
          - tests/pytests/scenarios
          - --ignore=tests/unit --ignore=tests/pytests/unit --ignore=tests/pytests/functional --ignore=tests/pytests/scenarios

    steps:
    - uses: actions/checkout@v3

    - name: Fetch Artifact
      uses: actions/download-artifact@v3
      with:
        name: Salt Onedir X86_64

    - name: Extract Artifact
      run: |
        mkdir salt-artifacts
        cp salt*tar.xz salt-artifacts/
        cd salt-artifacts
        tar -xvf salt*tar.xz

    - name: Run Tests
      uses: leleliu008/github-actions-vagrant@v2
      with:
        mem: 4096
        box: salt-project-ci/debian-11
        run: |
          sudo env SKIP_REQUIREMENTS_INSTALL=YES PATH=salt-artifacts/salt/bin:${PATH} \
            nox --force-color -e 'pytest-zeromq-3(coverage=True)' -- --color=yes \
            -vv --scripts-dir=salt-artifacts/salt --run-slow --ssh-tests --run-destructive ${{ matrix.test-paths }}
