name: Build onedir

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build onedir
      run: ./pkg/onedir.sh

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        path: salt*.tar.xz
