name: Build x86_64 RPM Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential devscripts debhelper

    - name: Link debian directory
      run: ln -s pkg/deb/debian debian

    - name: Build RPM PKG
      run: pkg/rpm/build.sh

    - name: ls dir
      run: ls `dirname ${{ github.workspace }}`

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: /home/runner/work/salt/salt*rpm

