---
name: Build Packaging Dependencies Onedir

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
    secrets:
      salt-repo-domain:
        required: true
      salt-repo-user:
        required: false
      salt-repo-pass:
        required: false


jobs:

  test-amazon-repo:
    name: Amazon Linux
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
        version:
          - "2"
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    environment: ${{ inputs.environment }}
    container: ghcr.io/saltstack/salt-ci-containers/amazonlinux:${{ matrix.version }}

    steps:
      - name: Setup Repo Base URL
        run: |
          if [ "${{ secrets.salt-repo-user }}" != "" ]; then
            BASE_URL="https://${{ secrets.salt-repo-user }}:${{ secrets.salt-repo-pass }}@${{ secrets.salt-repo-domain }}"
          else
            BASE_URL="https://{{ secrets.salt-repo-domain }}"
          fi
          echo "REPO_BASE_URL=$BASE_URL" >> "${GITHUB_ENV}"

      - name: Import GPG Key
        run: |
          rpm --import ${{ env.REPO_BASE_URL }}/amazon/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub

      - name: Import Repo File
        run: |
          curl -fsSL -o /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo ${{ env.REPO_BASE_URL }}/amazon/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}.repo
          echo baseurl=${{ env.REPO_BASE_URL }}/amazon/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }} >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo
          echo gpgkey=${{ env.REPO_BASE_URL }}/amazon/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo

      - name: Install Salt
        run: |
          yum clean expire-cache
          yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

      - name: Test `salt-call --local test.versions`
        run: |
          salt-call --local test.versions

      - name: Test `salt-call --local grains.items`
        run: |
          salt-call --local grains.items

      - name: Test `salt --version`
        run: |
          salt --version

      - name: Test `salt-master --version`
        run: |
          salt-master --version

      - name: Test `salt-minion --version`
        run: |
          salt-minion --version

      - name: Test `salt-ssh --version`
        run: |
          salt-ssh --version

      - name: Test `salt-syndic --version`
        run: |
          salt-syndic --version

      - name: Test `salt-api --version`
        run: |
          salt-api --version

      - name: Test `salt-cloud --version`
        run: |
          salt-cloud --version

  test-centos-repo:
    name: Centos
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
        version:
          - "7"
          - "stream8"
          - "stream9"
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    environment: ${{ inputs.environment }}
    container: ghcr.io/saltstack/salt-ci-containers/centos:${{ matrix.version }}

    steps:
      - name: Setup Repo Base URL
        run: |
          if [ "${{ secrets.salt-repo-user }}" != "" ]; then
            BASE_URL="https://${{ secrets.salt-repo-user }}:${{ secrets.salt-repo-pass }}@${{ secrets.salt-repo-domain }}"
          else
            BASE_URL="https://{{ secrets.salt-repo-domain }}"
          fi
          echo "REPO_BASE_URL=$BASE_URL" >> "${GITHUB_ENV}"

      - name: Import GPG Key
        run: |
          rpm --import ${{ env.REPO_BASE_URL }}/redhat/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub

      - name: Import Repo File
        run: |
          curl -fsSL -o /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo ${{ env.REPO_BASE_URL }}/redhat/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}.repo
          echo baseurl=${{ env.REPO_BASE_URL }}/redhat/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }} >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo
          echo gpgkey=${{ env.REPO_BASE_URL }}/redhat/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo

      - name: Install Salt
        run: |
          yum clean expire-cache
          yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

      - name: Test `salt-call --local test.versions`
        run: |
          salt-call --local test.versions

      - name: Test `salt-call --local grains.items`
        run: |
          salt-call --local grains.items

      - name: Test `salt --version`
        run: |
          salt --version

      - name: Test `salt-master --version`
        run: |
          salt-master --version

      - name: Test `salt-minion --version`
        run: |
          salt-minion --version

      - name: Test `salt-ssh --version`
        run: |
          salt-ssh --version

      - name: Test `salt-syndic --version`
        run: |
          salt-syndic --version

      - name: Test `salt-api --version`
        run: |
          salt-api --version

      - name: Test `salt-cloud --version`
        run: |
          salt-cloud --version

  test-debian-repo:
    name: Debian
    strategy:
      fail-fast: false
      matrix:
        include:
          - {"version": "10", "codename": "buster", "arch": "amd64"}
          - {"version": "10", "codename": "buster", "arch": "arm64"}
          - {"version": "11", "codename": "bullseye", "arch": "amd64"}
          - {"version": "11", "codename": "bullseye", "arch": "arm64"}
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    environment: ${{ inputs.environment }}
    container: ghcr.io/saltstack/salt-ci-containers/debian:${{ matrix.version }}

    steps:
      - name: Setup Repo Base URL
        run: |
          if [ "${{ secrets.salt-repo-user }}" != "" ]; then
            BASE_URL="https://${{ secrets.salt-repo-user }}:${{ secrets.salt-repo-pass }}@${{ secrets.salt-repo-domain }}"
          else
            BASE_URL="https://{{ secrets.salt-repo-domain }}"
          fi
          echo "REPO_BASE_URL=$BASE_URL" >> "${GITHUB_ENV}"

      - name: Update System
        run: |
          apt-get update -y
          apt-get install -y curl

      - name: Download GPG Key
        run: |
          curl -fsSL -o /usr/share/keyrings/SALT-PROJECT-GPG-PUBKEY-2023.gpg \
            ${{ env.REPO_BASE_URL }}/debian/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version}}/SALT-PROJECT-GPG-PUBKEY-2023.gpg

      - name: Setup Repo
        run: |
          echo "deb [signed-by=/usr/share/keyrings/SALT-PROJECT-GPG-PUBKEY-2023.gpg arch=${{ matrix.arch }}] ${{ env.REPO_BASE_URL }}/debian/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version}} ${{ matrix.codename }} main" | sudo tee /etc/apt/sources.list.d/salt.list

      - name: Install Salt
        run: |
          apt-get update
          apt-get install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api
          yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

      - name: Test `salt-call --local test.versions`
        run: |
          salt-call --local test.versions

      - name: Test `salt-call --local grains.items`
        run: |
          salt-call --local grains.items

      - name: Test `salt --version`
        run: |
          salt --version

      - name: Test `salt-master --version`
        run: |
          salt-master --version

      - name: Test `salt-minion --version`
        run: |
          salt-minion --version

      - name: Test `salt-ssh --version`
        run: |
          salt-ssh --version

      - name: Test `salt-syndic --version`
        run: |
          salt-syndic --version

      - name: Test `salt-api --version`
        run: |
          salt-api --version

      - name: Test `salt-cloud --version`
        run: |
          salt-cloud --version

  test-fedora-repo:
    name: Fedora
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
        version:
          - "36"
          - "37"
          - "38"
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    environment: ${{ inputs.environment }}
    container: ghcr.io/saltstack/salt-ci-containers/fedora:${{ matrix.version }}

    steps:
      - name: Setup Repo Base URL
        run: |
          if [ "${{ secrets.salt-repo-user }}" != "" ]; then
            BASE_URL="https://${{ secrets.salt-repo-user }}:${{ secrets.salt-repo-pass }}@${{ secrets.salt-repo-domain }}"
          else
            BASE_URL="https://{{ secrets.salt-repo-domain }}"
          fi
          echo "REPO_BASE_URL=$BASE_URL" >> "${GITHUB_ENV}"

      - name: Import GPG Key
        run: |
          rpm --import ${{ env.REPO_BASE_URL }}/fedora/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub

      - name: Import Repo File
        run: |
          curl -fsSL -o /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo ${{ env.REPO_BASE_URL }}/fedora/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}.repo
          echo baseurl=${{ env.REPO_BASE_URL }}/fedora/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }} >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo
          echo gpgkey=${{ env.REPO_BASE_URL }}/fedora/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version }}/SALT-PROJECT-GPG-PUBKEY-2023.pub >> /etc/yum.repos.d/salt-${{ inputs.salt-version }}.repo

      - name: Install Salt
        run: |
          yum clean expire-cache
          yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

      - name: Test `salt-call --local test.versions`
        run: |
          salt-call --local test.versions

      - name: Test `salt-call --local grains.items`
        run: |
          salt-call --local grains.items

      - name: Test `salt --version`
        run: |
          salt --version

      - name: Test `salt-master --version`
        run: |
          salt-master --version

      - name: Test `salt-minion --version`
        run: |
          salt-minion --version

      - name: Test `salt-ssh --version`
        run: |
          salt-ssh --version

      - name: Test `salt-syndic --version`
        run: |
          salt-syndic --version

      - name: Test `salt-api --version`
        run: |
          salt-api --version

      - name: Test `salt-cloud --version`
        run: |
          salt-cloud --version

  test-ubuntu-repo:
    name: Ubuntu
    strategy:
      fail-fast: false
      matrix:
        include:
          - {"version": "20.04", "codename": "focal", "arch": "amd64"}
          - {"version": "20.04", "codename": "focal", "arch": "arm64"}
          - {"version": "22.04", "codename": "jammy", "arch": "amd64"}
          - {"version": "22.04", "codename": "jammy", "arch": "arm64"}
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    environment: ${{ inputs.environment }}
    container: ghcr.io/saltstack/salt-ci-containers/ubuntu:${{ matrix.version }}

    steps:
      - name: Setup Repo Base URL
        run: |
          if [ "${{ secrets.salt-repo-user }}" != "" ]; then
            BASE_URL="https://${{ secrets.salt-repo-user }}:${{ secrets.salt-repo-pass }}@${{ secrets.salt-repo-domain }}"
          else
            BASE_URL="https://{{ secrets.salt-repo-domain }}"
          fi
          echo "REPO_BASE_URL=$BASE_URL" >> "${GITHUB_ENV}"

      - name: Update System
        run: |
          apt-get update -y
          apt-get install -y curl

      - name: Download GPG Key
        run: |
          curl -fsSL -o /usr/share/keyrings/SALT-PROJECT-GPG-PUBKEY-2023.gpg \
            ${{ env.REPO_BASE_URL }}/ubuntu/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version}}/SALT-PROJECT-GPG-PUBKEY-2023.gpg

      - name: Setup Repo
        run: |
          echo "deb [signed-by=/usr/share/keyrings/SALT-PROJECT-GPG-PUBKEY-2023.gpg arch=${{ matrix.arch }}] ${{ env.REPO_BASE_URL }}/ubuntu/${{ matrix.version }}/${{ matrix.arch }}/minor/${{ inputs.salt-version}} ${{ matrix.codename }} main" | sudo tee /etc/apt/sources.list.d/salt.list

      - name: Install Salt
        run: |
          apt-get update
          apt-get install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api
          yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

      - name: Test `salt-call --local test.versions`
        run: |
          salt-call --local test.versions

      - name: Test `salt-call --local grains.items`
        run: |
          salt-call --local grains.items

      - name: Test `salt --version`
        run: |
          salt --version

      - name: Test `salt-master --version`
        run: |
          salt-master --version

      - name: Test `salt-minion --version`
        run: |
          salt-minion --version

      - name: Test `salt-ssh --version`
        run: |
          salt-ssh --version

      - name: Test `salt-syndic --version`
        run: |
          salt-syndic --version

      - name: Test `salt-api --version`
        run: |
          salt-api --version

      - name: Test `salt-cloud --version`
        run: |
          salt-cloud --version
